server:
  port: 8082

spring:
  redis:
    host: 172.16.30.103
    port: 6379
    password:
  application:
    name: weather-report-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000