server:
  port: 8762

spring:
  application:
    name: eureka2-service
  cloud:
    config:
      enabled: false

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/